{{- if not .Values.hub.existingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub-secret.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $values := merge dict .Values }}
  {{- /* preserve behavior of deprecated hub.extraConfigMap */}}
  {{- $_ := set $values "custom" (merge dict $values.custom .Values.hub.extraConfigMap) }}
  {{- /* passthrough subset of Chart / Release */}}
  {{- $_ := set $values "Chart" (dict "Name" .Chart.Name "Version" .Chart.Version) }}
  {{- $_ := set $values "Release" (pick .Release "Name" "Namespace" "Service") }}
  values.yaml: {{ $values | toYaml | b64enc | quote }}

  {{- with .Values.hub.db.password }}
  # Used to mount MYSQL_PWD or PGPASSWORD on hub pod
  hub.db.password: {{ . | b64enc | quote }}
  {{- end }}

  {{- range $key, $service := .Values.hub.services }}
  {{- if $service.apiToken }}
  # Potentially used to mount on an external service in the k8s cluster
  services.token.{{$key}}: {{ $service.apiToken | b64enc | quote }}
  {{- end }}
  {{- end }}

  # During Helm template rendering, these values are set using the named
  # templates by a logic having the following priority:
  #
  # 1. Return an explicitly set value
  # 2. Return an existing key's value in the current k8s Secret
  # 3. Return an autogenerated value
  #
  # JupyterHub.proxy_auth_token:  for hub to proxy-api authorization
  # JupyterHub.cookie_secret:     for cookie encryption
  # CryptKeeper.keys:             for auth state encryption
  #
  JupyterHub.proxy_auth_token: {{ include "jupyterhub.config.JupyterHub.proxy_auth_token" . | required "This should not happen: blank output from 'jupyterhub.config.JupyterHub.proxy_auth_token' template" | b64enc | quote }}
  JupyterHub.cookie_secret: {{ include "jupyterhub.config.JupyterHub.cookie_secret" . | required "This should not happen: blank output from 'jupyterhub.config.JupyterHub.cookie_secret' template" | b64enc | quote }}
  CryptKeeper.keys: {{ include "jupyterhub.config.CryptKeeper.keys" . | required "This should not happen: blank output from 'jupyterhub.config.CryptKeeper.keys' template" | b64enc | quote }}
{{- end }}
