kind: Secret
apiVersion: v1
metadata:
  name: hub-secret
type: Opaque
data:
  proxy.token: {{ .Values.proxy.secretToken | b64enc | quote }}
  {{ if .Values.hub.cookieSecret }}
  hub.cookie-secret: {{ .Values.hub.cookieSecret | b64enc | quote }}
  {{- end }}
  {{ range $key, $value := .Values.hub.services -}}
  {{ if $value.apiToken }}
  services.token-{{$key}}: {{ $value.apiToken | b64enc | quote }}
  {{ end }}
  {{ end }}
