apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cull-deployment
  namespace: {{ .Values.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cull-pod
    spec:
      containers:
        - name: cull-container
          image: data8/jupyterhub-k8s-cull:master
          command:
            - /bin/sh
            - -c
          args: ['python /srv/cull/cull_idle_servers.py --timeout={{ .Values.cull.timeout }} --cull_every={{ .Values.cull.every }} --url=http://${HUB_SERVICE_HOST}:${HUB_SERVICE_PORT}/hub']
          env:
          - name: JPY_API_TOKEN
            valueFrom:
              configMapKeyRef:
                name: hub-config
                key: token.culler
