apiVersion: apps/v1
kind: Deployment
metadata:
  name: taintmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taintmanager
  template:
    metadata:
      labels:
        app: taintmanager
    spec:
      containers:
        - image: lthub/taintmanager
          imagePullPolicy: IfNotPresent
          name: taintmanager
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
      restartPolicy: Always
