{{ if .Values.builder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: builder
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
spec:
  type: LoadBalancer
  selector:
    name: builder-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
---
kind: Secret
apiVersion: v1
metadata:
  name: builder-secret
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
type: Opaque
data:
  config.json: |
    {{ b64enc (printf "{\"auths\": { \"https://%s\": { \"email\": \"not@val.id\", \"auth\": \"%s\" } } }" .Values.builder.registry.host (b64enc (printf "%s:%s" .Values.builder.registry.username .Values.builder.registry.password) ) ) }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: builder-config-{{ default .Release.Revision .Values.revisionOverride }}
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
data:
  builder.push-secret: builder-secret
  hub.public-url: {{ .Values.hub.publicURL | quote }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: builderhub-deployment
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: builder-pod
        {{ if .Values.builder.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.builder.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      volumes:
      - name: config
        configMap:
          name: builder-config-{{ default .Release.Revision .Values.revisionOverride }}
      containers:
      - name: builder-container
        image: {{ .Values.builder.image.name }}:{{ .Values.builder.image.tag }}
        volumeMounts:
          - mountPath: /etc/builderhub/config/
            name: config
        resources:
{{ toYaml .Values.builder.resources | indent 12}}
        imagePullPolicy: IfNotpresent
        env:
        - name: BUILD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8585
            name: builder
{{- end }}
