{{- if .Values.httpRoute.enabled -}}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "jupyterhub.httpRoute.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.httpRoute.Gateway.Name }}
      namespace: {{ .Values.httpRoute.Gateway.Namespace }}
  {{- with .Values.httpRoute.Hostnames }}
  hostnames:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: proxy-public
          port: 80

---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "jupyterhub.httpRoute.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /hub/login
  targetRef:
    group: ""
    kind: Service
    name: proxy-public
{{- end }}
