{{- range $name, $details := .Values.singleuser.extraFiles }}
{{- /* Make the key RFC 1035 Label Naming compliant */}}
{{- $name = $name | lower | replace "_" "-" | replace "." "-" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.singleuser.fullname" $ }}-{{ $name }}
  labels:
    {{- include "jupyterhub.labels" $ | nindent 4 }}
type: Opaque
{{- with include "jupyterhub.extraFiles.data" (dict $name $details) }}
data:
  {{- . | nindent 2 }}
{{- end }}
{{- with include "jupyterhub.extraFiles.stringData" (dict $name $details) }}
stringData:
  {{- . | nindent 2 }}
{{- end }}
{{- end }}
