{{ define "jupyterhub.imagePuller.daemonset" }}
# template that returns a image-puller daemonset, used for
# - pre-helm-upgrade image pulling (pulls images before helm upgrades, temporary)
# - continuous image pulling (pulls images for cluster autoscalers, persistent)
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .name }}
  labels:
    app: jupyterhub
    component: {{ .name }}
    release: {{ .top.Release.Name }}
    heritage: {{ .top.Release.Service }}
    {{ if .hook }}
    hub.jupyter.org/deletable: "true"
    {{ end}}
  annotations:
    {{ if .hook }}
    # create it before installs/upgrades ...
    "helm.sh/hook": pre-install,pre-upgrade
    # ... and before the image-awaiter job ...
    "helm.sh/hook-weight": "-10"
    # ... but then delete it
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    {{ end }}
spec:
  selector:
    matchLabels:
        app: jupyterhub
        component: {{ .name }}
        release: {{ .top.Release.Name }}
        heritage: {{ .top.Release.Service }}
  template:
    metadata:
      labels:
        app: jupyterhub
        component: {{ .name }}
        release: {{ .top.Release.Name }}
        heritage: {{ .top.Release.Service }}
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      initContainers:
      - name: image-pull-singleuser
        image: {{ .top.Values.singleuser.image.name }}:{{ .top.Values.singleuser.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ if not .top.Values.singleuser.cloudMetadata.enabled }}
      - name: image-pull-metadata-block
        image: {{ .top.Values.singleuser.networkTools.image.name }}:{{ .top.Values.singleuser.networkTools.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ end }}
      {{ range $k, $v := .top.Values.prePuller.extraImages }}
      - name: image-pull-{{ $k }}
        image: {{ $v.name }}:{{ $v.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ end }}
      containers:
      - name: pause
        image: {{ .top.Values.prePuller.pause.image.name }}:{{ .top.Values.prePuller.pause.image.tag }}
{{- end }}
