{{- /*
ServiceAccount for the pre-puller hook's image-awaiter-job
*/}}
{{- if .Values.prePuller.hook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.hook-image-awaiter-serviceaccount.fullname" . }}
  {{- with .Values.hub.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
{{- end }}
