#!/bin/bash

export KUBECONFIG=${PWD}/.kube/config
export MINIKUBE_HOME=${PWD}/.minikube
export HELM_HOME=${PWD}/.helm
mkdir -p "${PWD}/.kube"
touch "${PWD}/.kube/config"

export KUBE_VERSION=1.10.0
export MINIKUBE_VERSION=0.28.2
export HELM_VERSION=2.9.1
export KUBEVAL_VERSION=0.7.1
export PATH="${PWD}/bin:${PATH}"
