#!/bin/bash
# NOTE: The script should be executed as a part of ci/run!
# NOTE: As this script exports environment variables, it should be run with
#       `source ci/4-setup-cluster-env` in order for them to be made available.

# SCRIPT SUMMARY
# --------------
# 1. Export docker environment variables
# 2. Export development and testing environment variables

# Set shell options
# -e : Exit immediately if a command exits with a non-zero status.
# -u : Treat unset variables as an error when substituting.
# -x : Print commands and their arguments as they are executed.
set -ux

# 1.
if set +u && [[ -z "${CICD}" ]] && set -u; then
  # LOCAL
  eval $(minikube docker-env)
fi

# 2.
export MINIKUBE_IP=$(minikube ip)
export HUB_API_URL=http://$MINIKUBE_IP:31212/hub/api

# Since this script will be sourced, revert to previous shell options
# FIXME: we are just guessing what the previous options were now
set +ux
