#!/bin/bash
# NOTE: The script should be executed from the repo directory

# SCRIPT SUMMARY
# --------------
# 1. Install the Helm chart using minikube-config.yaml
# 2. Wait for the hub to become responsive
# 3. Ensure a user can be created, spawned and culled using the hub's API
#    http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml

# Set shell options
# -e : Exit immediately if a command exits with a non-zero status.
# -u : Treat unset variables as an error when substituting.
# -x : Print commands and their arguments as they are executed.
set -eux

# Install chart
echo "installing chart"
helm upgrade jh \
  --install \
  --namespace jh \
  --values ci/6-tests-config.yaml \
  ./jupyterhub/

echo "waiting for servers to become responsive"
until curl --fail --silent --show-error $HUB_API_URL; do
    kubectl describe pod --namespace jh
    kubectl get pod      --namespace jh
    sleep 10
done

# Make various request using the hub's API
# -
echo "getting jupyterhub version and info"
curl --silent --show-error $HUB_API_URL | grep version

echo "running pytest"
# -v --verbose     : increase verbosity
# ---capture=no  : no capture of output to stdout or stderr
# -x --exitfirst   : exit instantly on first error or failed test
pytest --verbose --capture=no --exitfirst
