#!/bin/bash

# NOTE: The script should be executed from the repo directory

# SCRIPT SUMMARY
# --------------
# 1. Deletes

# Set shell options
# -e : Exit immediately if a command exits with a non-zero status.
# -u : Treat unset variables as an error when substituting.
# -x : Print commands and their arguments as they are executed.
set -eux

source ci/0-setup-env
minikube delete

rm -rf .kube/ .minikube/ .helm/
