#!/bin/bash

# NOTE: The script should be executed from the repo directory

# SCRIPT SUMMARY
# --------------
# Everything is just meant to run...

# TROUBLESHOOTING
# ---------------
# NOTE: Tested only on Ubuntu
# rm -rf .kube/ .minikube/ .helm/

# Set shell options
# -e : Exit immediately if a command exits with a non-zero status.
# -u : Treat unset variables as an error when substituting.
# -x : Print commands and their arguments as they are executed.
set -eux

source ci/0-setup-env
ci/1-setup-binaries
ci/2-lint-and-validate
ci/3-setup-k8s
ci/4-build-chart-and-images
ci/5-run-tests
