#!/bin/bash

# NOTE: The script should be executed from the repo directory

# SCRIPT SUMMARY
# --------------
# Runs everything that needs to run in order to run CI except setup of
# virtualbox for local developments.

# TROUBLESHOOTING
# ---------------
# 0. Make sure you have virtualbox which is required by minikube
# 1. Run the `ci/clean` script

source ci/0-setup-env; set -eux
ci/1-setup-binaries
ci/2-lint-and-validate
ci/3-setup-k8s
source ci/4-setup-cluster-env; set -eux
ci/5-build-chart-and-images

ci/6-run-tests

if set +u && [[ -z "${CICD}" ]] && set -u; then
  # LOCAL
  echo "Kubernetes dashboard http://$MINIKUBE_IP:30000"
  echo "JupyterHub at http://$MINIKUBE_IP:31212"
  echo "JupyterHub API $HUB_API_URL"
fi
