#!/bin/bash
# Parse the output.json created by the Sphinx linkchecker
# and summarise broken and redirected links

set -eu
LINKCHECK="$1"

N_BROKEN=$(jq -r 'select(.status=="broken") | reduce inputs as $s(0;.+1)' "$LINKCHECK")
N_REDIRECTED=$(jq -r 'select(.status=="redirected") | reduce inputs as $s(0;.+1)' "$LINKCHECK")

if [ "$N_BROKEN" -gt 0 ]; then
    printf "\n\033[31;1m%s\033[0m\n" "Broken links"
    jq -r 'select(.status=="broken") | "\(.filename):\(.lineno) \(.uri)\n    \(.info)"' "$LINKCHECK"
fi

if [ "$N_REDIRECTED" -gt 0 ]; then
    printf "\n\033[35;1m%s\033[0m\n" "Redirected links"
    jq -r 'select(.status=="redirected") | "\(.filename):\(.lineno) \(.uri)\n    \(.code) \(.info)"' "$LINKCHECK"
fi
