#!/bin/bash
set -eu

## set TRAVIS_COMMIT_RANGE if it is unset on a local CI run
##
## NOTE: Use an open ended range from the upstream or origin master branch to the
##       current state including unstaged changes.
##
if [ -z ${TRAVIS_COMMIT_RANGE:-} ]; then
    if git remote -v | grep --word-regex upstream; then
        GIT_REMOTE=upstream/
    elif git remote -v | grep --word-regex origin; then
        GIT_REMOTE=origin/
    fi
    export TRAVIS_COMMIT_RANGE=${GIT_REMOTE:-}master..
fi

echo "build images and update the default values.yaml to reference them"
chartpress --commit-range ${TRAVIS_COMMIT_RANGE}
git --no-pager diff

echo "load the images the kind cluster"
python3 ci/kind-load-docker-images.py --kind-cluster $KIND_CLUSTER --values ./jupyterhub/values.yaml

echo "install our deployment"
helm upgrade jh-dev ./jupyterhub \
    --install \
    --namespace jh-dev \
    --values dev-config.yaml \
    --wait

echo "waiting for hub and proxy to become responsive"
kubectl rollout status deployment/proxy --timeout 1m
kubectl rollout status deployment/hub --timeout 1m

echo "couple a localhost port with svc/proxy-public to access JupyterHub API"
kubectl port-forward svc/proxy-public 8080:80 > /dev/null 2>&1 &
