# -*- mode: ruby -*-
# vi: set ft=ruby :

# See the README for details

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "3072"
     vb.cpus = 2
  end

  # mount the repo to '/zero-to-jupyterhub-k8s' in the VM
  config.vm.synced_folder "./", "/zero-to-jupyterhub-k8s"

  config.vm.provision "shell", path: "vagrant-bionic-setup.sh"
end
