FROM gcr.io/data-8/jupyterhub-k8s-user-base:2291af02385fee6c81b4de5cccfc4f5fbbf58a83

MAINTAINER Ryan Lovett <rylo@berkeley.edu>

USER root

ADD install-rstudio-server.bash /usr/local/sbin/install-rstudio-server.bash
RUN /usr/local/sbin/install-rstudio-server.bash

USER $NB_USER

ADD install-nbrsessionproxy.bash /usr/local/sbin/install-nbrsessionproxy.bash
RUN /usr/local/sbin/install-nbrsessionproxy.bash
